name: DevSecOps-FinalLab

on:
  push:
    branches:
      - feature-finalLab

jobs:
  Docker-build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest

  Trivy-scan-docker-image:
    needs: Docker-build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      # Step 2: Log in to Docker Hub (optional if private image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Pull the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest

      # Scan a Docker image
      - name: Run Trivy Scan on Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest .
          trivy image --severity CRITICAL,HIGH,MEDIUM,LOW --exit-code 1 ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest

      # OR Scan the source code
      - name: Run Trivy Scan on Source Code (Filesystem)
        run: |
          trivy fs --severity CRITICAL,HIGH,MEDIUM,LOW --exit-code 1 .

      # OR Scan with custom thresholds (using exit codes)
      - name: Run Trivy Scan with Custom Thresholds
        run: |
          trivy fs --severity CRITICAL,HIGH --exit-code 1 --ignore-unfixed .