name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js for the React Native project
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Build the project (if necessary for analysis)
      - name: Build the project
        run: npm run build

      # Set up Java (required by SonarCloud)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Run SonarCloud analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: . # Adjust this if your React Native project is in a subdirectory
