name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  SCA-dependency-check:
    #needs: SAST-SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: ECHO ENV TOKEN
        run: |
          echo ${{ secrets.SNYK_TOKEN }}