name: DevSecOps-FinalLab

on:
  push:
    branches:
      - main

jobs:
  Docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devSecOps-finalLab:latest
  Trivy-scan-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub (optional if private image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devSecOps-finalLab:latest .

      # Step 4: Scan the Docker image with Trivy
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          scan-type: fs
          image-ref: ${{ secrets.DOCKER_USERNAME }}/devSecOps-finalLab:latest
          format: table
          severity: HIGH,CRITICAL
        continue-on-error: true