name: DevSecOps-FinalLab

on:
  push:
    branches:
      - feature-finalLab

jobs:
  Docker-build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest

  docker-build-and-run:
    runs-on: self-hosted
    needs: Docker-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest

      - name: Run app in Docker container
        run: |
          docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest
          
      - name: Check running Docker containers
        run: docker ps