name: DevSecOps-FinalLab

on:
  push:
    branches:
      - feature-finalLab

jobs:
  Docker-build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest
  Deploy-to-AWS-EC2:
    name: Deploy to AWS EC2
    needs: Docker-build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            # Update Docker image and restart the container
            docker pull ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest
            docker stop devsecops-finallab || true
            docker rm devsecops-finallab || true
            docker run -d --name devsecops-finallab -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest