name: DevSecOps-FinalLab

on:
  push:
    branches:
      - feature-finalLab

jobs:
  SAST-SonarCloud:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js for the React Native project
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Build the project (if necessary for analysis)
      - name: Build the project
        run: npm run build

      # Set up Java (required by SonarCloud)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Run SonarCloud analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: . # Adjust this if your React Native project is in a subdirectory
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.branch.name=feature-finalLab
            -Dsonar.sources=src
            -Dsonar.exclusions=**/node_modules/**,**/android/**,**/ios/**
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      # Check SonarCloud for High-Severity Issues
      - name: Check for High-Severity Issues
        run: |
          response=$(curl -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/issues/search?componentKeys=${{ secrets.SONAR_PROJECTKEY }}&severities=MINOR,MAJOR&statuses=OPEN")
          count=$(echo "$response" | jq '.total')
          echo "Found $count medium-severity (MAJOR) OR low-severity (MINOR) issues."

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  SCA-SNYK:
    needs: SAST-SonarCloud
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for React Native
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Step 5: Authenticate with Snyk using the token from GitHub Secrets
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Step 6: Run Snyk test to check for vulnerabilities
      - name: Run Snyk Test
        run: |
          snyk test --all-projects --json > snyk-results.json || true

      # Optional: Monitor dependencies with Snyk (submit project to Snyk)
      - name: Monitor with Snyk
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 4: Run Snyk to test for vulnerabilities
      - name: Snyk Test
        id: snyk
        run: snyk test --severity-threshold=medium

      # Step 5: Fail the pipeline if vulnerabilities are found
      - name: Fail on vulnerabilities
        if: failure()
        run: |
          echo "High/Medium/Low vulnerabilities detected. Failing pipeline."
          exit 1