name: DevSecOps-FinalLab

on:
  push:
    branches:
      - feature-finalLab

jobs:
  Deploy-to-AWS-EC2:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            # Update Docker image and restart the container
            docker pull ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest
            docker stop devsecops-finallab || true
            docker rm devsecops-finallab || true
            docker run -d --name devsecops-finallab -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/devsecops-finallab:latest